version: "3"
networks:
  empathy_network:
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    networks:
      - empathy_network
    environment:
      - "cluster.name=elasticsearch-cluster" #Sets the cluster name
      - "node.name=elasticsearch" #Sets node name
      - "network.host=0.0.0.0"  #Sets binding IP to all
      - "xpack.security.enabled=false" #Disables xpack security
      - "xpack.monitoring.enabled=true" #Disables xpack monitoring
      - "xpack.monitoring.collection.enabled=true"
      - "xpack.watcher.enabled=false" #Disables xpack watcher
      - "xpack.ml.enabled=false" #Disables xpack machine learning
      - "bootstrap.memory_lock=true"  #Disables memory swap
      - "discovery.type=single-node" #Disable bootstrap checks
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" #Sets allocated memory
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - "IPC_LOCK"
    volumes:
      - "./volumes/elasticsearch/data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
  search-service:
    image: search-service@sha256:a37d560e4b5a72468f780969efd5a04be5dcd6c78bb90d4febec274140ac57ba
    container_name: search-service
    networks:
      - empathy_network
    environment:
      - JAVA_HEAP=256m
      - SPRING_PROFILES_ACTIVE=plugins-files.local,plugins-configs.local,client.startup.file
      - COLLECTION_NAMING_CONFIG_PROVIDER=local
      - PLUGINS_FILES_LOCAL_PATH=/srv/plugins
      - COLLECTION_NAMING_CONFIG_LOCAL_PATH=/srv/collection-config/collection-name-config.json
      - COLLECTION_NAMING_CONFIG_INSTANCE=test
      - PLUGINS_CONFIGS_LOCAL_PATH=/srv/plugin-configs
      - CONTEXTUALIZE_ENABLED=false
      - ELASTIC_READ_URL=http://elasticsearch:9200
      - TRACKING_ENABLED=false
    volumes:
      - "./srv/plugins:/srv/plugins"
      - "./srv/plugin-configs:/srv/plugin-configs"
      - "./srv/collection-config:/srv/collection-config"
    ports:
      - 8080:8080
  indexing_job:
    build:
      context: ./indexing
      dockerfile: Dockerfile
    container_name: indexing-job-local
    volumes:
      - "./indexing/scripts:/scripts"
      - "./collection-files:/collection-files"
    depends_on:
      - elasticsearch
